### PR TITLE
fix(types): export component types needed for consumer declaration emit

### LINKED ISSUE #1061: Re-exporting VChart from a library with `declaration: true` fails with TS4023 / TS2742
### Confirmation

- [x] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue ECharts into your project?

ES Module imports

### Versions

```sh
├── echarts@6.1.0
  ├── typescript@5.9.3
  ├─┬ vue-echarts@8.3.0
  │ ├── echarts@6.1.0 deduped
  │ └── vue@3.5.43 deduped
  └─┬ vue@3.5.43
    └── typescript@5.9.3 deduped
```

### Details

A library that re-exports the default export (`VChart`) and emits its own `.d.ts` with `declaration: true` fails to compile with `vue-echarts@8.3.0`:

```ts
import VChart from "vue-echarts";
export const MyChart = VChart;
```

```
src/index.ts(4,14): error TS2742: The inferred type of 'MyChart' cannot be named without a reference to '../node_modules/vue-echarts/dist/index-BujxhN-1'. This is likely not portable. A type annotation is necessary.
src/index.ts(4,14): error TS4023: Exported variable 'MyChart' has or is using name 'CoordinateSystemDataLayout' from external module ".../node_modules/echarts/types/dist/shared" but cannot be named.
src/index.ts(4,14): error TS4023: Exported variable 'MyChart' has or is using name 'ECActionEvent' from external module ".../node_modules/echarts/types/dist/shared" but cannot be named.
src/index.ts(4,14): error TS4023: Exported variable 'MyChart' has or is using name 'SlotSymbol' from external module ".../node_modules/@vue/runtime-core/dist/runtime-core" but cannot be named.
src/index.ts(4,14): error TS4023: Exported variable 'MyChart' has or is using name 'ZRenderType' from external module ".../node_modules/echarts/types/dist/shared" but cannot be named.
```

The component type lives in an internal chunk (`dist/index-*.d.ts`) and is built from `PublicComponent`, `PublicMethods` and `SlotsTypes`, none of which are exported from the package entry point. TypeScript has no public path to name the type, so it tries to inline it and hits non-exported names from `echarts` and `@vue/runtime-core`.

Exporting those three types from `vue-echarts` makes the build pass; the emitted declaration then reads `import("vue-echarts").PublicComponent<...>`. Proposed fix in #1060.

### Reproduction

https://github.com/p-morel-92/vue-echarts-ts4023-repro

### PR DESCRIPTION
**Pull request by p-morel-92**
Fixes #1061

## Problem

A library that re-exports the default export (`VChart`) and emits its own `.d.ts` with `declaration: true` fails to compile with 8.3.0:

```ts
import VChart from "vue-echarts";
export const MyChart = VChart;
```

```
error TS2742: The inferred type of 'MyChart' cannot be named without a reference to '../node_modules/vue-echarts/dist/index-BujxhN-1'. This is likely not portable. A type annotation is necessary.
error TS4023: Exported variable 'MyChart' has or is using name 'ZRenderType' from external module ".../echarts/types/dist/shared" but cannot be named.
error TS4023: Exported variable 'MyChart' has or is using name 'SlotSymbol' from external module ".../@vue/runtime-core/dist/runtime-core" but cannot be named.
```

The component type is built from `PublicComponent`, `PublicMethods` and `SlotsTypes`, which live in an internal chunk and are not reachable from any public entry point. TypeScript cannot name the type through `vue-echarts`, falls back to inlining it, and hits non-exported names from `echarts` and `@vue/runtime-core`.

Reproduction: https://github.com/p-morel-92/vue-echarts-ts4023-repro

## Fix

- `src/index.ts`: export `PublicComponent`, `PublicMethods` and `SlotsTypes` as types, so every name reachable from the component type has a public path.
- `tsconfig.package.json`: enable `declaration: true` so the package-level type test exercises the same declaration-emit path a consumer library would hit.
- `package-tests/consumer-declaration-emit.test-d.ts`: regression test that re-exports the component and wraps it in an object; fails with TS4023/TS2742 without this fix.

## Impact

Type-only additions, no runtime change. Existing exports untouched.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -8,3 +8,6 @@ export interface VChartSlotsExtension {
 export default ECharts;
 export * from "./ECharts";
 export type { AutoResize, LoadingOptions } from "./types";
+export type { PublicComponent } from "./types";
```
Comment (kingyue737) [inline src/index.ts]: nit: this export can be folded into the one above.

**Review by kingyue737 — APPROVED** [review]
LGTM

The only added commitment is that renames of the exported types become breaking changes — which should be rare.

File: src/index.ts (hunk 1 above)
Comment (p-morel-92) [reply src/index.ts]: Updated :+1:
