### ISSUE TITLE
vue-echarts doesn't work on vue 2.6.14

### ISSUE THREAD

**Issue by NaserAhadi** [ecomfe/vue-echarts#671]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
"vue": "^2.6.14",    
"echarts": "^5.4.0",
"vue-echarts": "^6.2.3",
```

### Details

Hi
I installed vue-echarts on my project and I did every thing based on documentation for vue version 2, but when I add one example of documentation it has error which it says `defineComponent` is not a function.
after that I get a new error which it says `vue@2.6.14`  and `vue-template-compiler@2.7.8` work not correctly but I check the version of both are the same.
And because of these error I even can't run the project.

### Reproduction

https://github.com/NaserAhadi/vue-echarts-test

**Comment by Justineo** [comment]
If you are using `vue@2.6.14` then you should also use `vue-template-compiler@2.6.14`.
